import type {Metadata} from "next";

import "./globals.css";

import Link from "next/link";

import {inter, monserrat} from "./ui/fonts";

export const metadata: Metadata = {
  title: "Demo Streaming app",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.className} grid min-h-screen grid-rows-[90px,1fr,120px] md:grid-rows-[70px,1fr,120px]`}
      >
        <header className="bg-blue-400 py-4">
          <div className="mx-auto flex max-w-sm flex-col items-center justify-between gap-2 md:max-w-screen-xl md:flex-row md:gap-0">
            <Link href="/">
              <h1 className={`${inter.className} text-lg font-bold leading-normal md:text-2xl`}>
                DEMO Streaming
              </h1>
            </Link>
            <nav className="flex w-full items-center justify-between gap-4 font-medium md:w-auto md:justify-normal">
              <button
                className="px-2 py-1 transition-colors hover:bg-sky-100 hover:text-blue-600 md:px-4 md:py-2"
                type="button"
              >
                Log In
              </button>
              <button className="bg-slate-900 px-2 py-1 md:px-4 md:py-2" type="button">
                Start your free trial
              </button>
            </nav>
          </div>
        </header>
        <main>{children}</main>
        <footer className="bg-slate-900 py-4">
          <p className="mx-auto max-w-sm font-medium md:max-w-screen-xl">
            Home | Terms and Conditions | privacy policy | help | manage Account
          </p>
        </footer>
      </body>
    </html>
  );
}
